### PR TITLE
Fixed import of feedparser on Linux version of calibre

### PR DESCRIPTION
**Pull request by sbobovyc**
After I installed your plugin in Calibre 2.55 on Ubuntu 16.04, Calibre threw an import error. I fixed this by having a different import statement based on the operating system. I've tested these changes on Windows and Linux, but not on OS X.

### CODE REVIEW

**Comment by steinarb** [comment]
It seems to work like before on Windows.

Will try debian jessie as well before merging.

**Comment by steinarb** [comment]
It failed on debian jessie.  Stack trace below.

Note that I'm running the calibre maintainer's linux package, rather than the debian packaged version of calibre.  This is because the calibre maintainer immediately rejects bug reports based on a distro-packaged version of calibre.

I use the following command line (as root) to install/update calibre on debian jessie:
`wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"`

Here's the standard out, including a stack trace, from a calibre failing to bring up opds-reader with this pull request applied:
```
sb@lorenzo:~/git/opds-reader/calibre_plugin$ git checkout -b sbobovyc-master master
Switched to a new branch 'sbobovyc-master'
sb@lorenzo:~/git/opds-reader/calibre_plugin$ git pull https://github.com/sbobovyc/opds-reader.git master
remote: Counting objects: 4, done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), done.
From https://github.com/sbobovyc/opds-reader
 * branch            master     -> FETCH_HEAD
Updating 8b79f9b..cc36607
Fast-forward
 calibre_plugin/model.py | 14 ++++++++++----
 1 file changed, 10 insertions(+), 4 deletions(-)
sb@lorenzo:~/git/opds-reader/calibre_plugin$ calibre-customize -b .
Plugin updated: OPDS Client (1, 0, 0)
sb@lorenzo:~/git/opds-reader/calibre_plugin$ calibre-debug -g
calibre 2.56  embedded-python: True is64bit: True
Linux-4.4.0-0.bpo.1-amd64-x86_64-with-debian-8.4 Linux ('64bit', 'ELF')
('Linux', '4.4.0-0.bpo.1-amd64', '#1 SMP Debian 4.4.6-1~bpo8+1 (2016-03-20)')
Python 2.7.9
Linux: ('debian', '8.4', '')
Successfully initialized third party plugins: OPDS Client
Starting up...
Traceback (most recent call last):
  File "site-packages/calibre/gui2/ui.py", line 152, in __init__
  File "site-packages/calibre/gui2/ui.py", line 166, in init_iaction
  File "site-packages/calibre/customize/__init__.py", line 603, in load_actual_plugin
  File "importlib/__init__.py", line 37, in import_module
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.opds_client.ui", line 9, in <module>
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.opds_client.main", line 12, in <module>
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.opds_client.model", line 15, in <module>
ImportError: cannot import name parse
Started up in 1.26 seconds with 395 books
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
```

**Comment by steinarb** [comment]
I didn't understand what "close and comment" meant,... now I do...

**Comment by steinarb** [comment]
Note that I'm still willing to merge the pull request if you can make it work with my debian setup as well.

**Comment by sbobovyc** [comment]
Maybe Ubuntu's packaged version of calibre is different from the maintainer version you are using. I will try to install calibre on Ubuntu with the method you described and then test your plugin.

**Comment by steinarb** [comment]
If the Ubuntu package is anything like the package in debian (in fact it probably is exactly the same as the package in debian testing) the package depends on python itself, and other python packages in their debian packaged form, while the maintainer's version bundles everything (python, Qt, all the used python libraries).

Actually, I prefer the debian package approach, but I switched so I could make calibre bug reports without having them be automatically rejected.

**Comment by sbobovyc** [comment]
Maintainer's package worked just fine on Ubuntu with your plugin so on my Linux clients, I will switch to it.

**Comment by steinarb** [comment]
OK, then this pull request won't be needed.  Closing the pull request.

**Pull request closed without merging**
